version: '3.8'

services:
  radio-app:
    build: .
    container_name: radio-dedalos-app-v2
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=host.docker.internal
    volumes:
      - ./public:/app/public
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    networks:
      - radio-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: radio-nginx-v2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-available:/etc/nginx/sites-available
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - radio-app
    networks:
      - radio-network
    restart: unless-stopped

networks:
  radio-network:
    driver: bridge